### ISSUE TITLE
Error when specifying an error function

### ISSUE THREAD

**Issue by WinAuthFan** [bips-hb/neuralnet#36]
```
# This is the example from ?neuralnet
library(neuralnet)
nn <- neuralnet(Species == "setosa" ~ Petal.Length + Petal.Width, iris, linear.output = FALSE)

# The default error function is half of SSE, as seen here:
nn$err.fct
# function (x, y) 
# {
#     1/2 * (y - x)^2
# }


# Now, let's specify this error function. We will use the exact same error function as the default:
my.err.fct = function (x, y) 
{
    1/2 * (y - x)^2
}
nn <- neuralnet(Species == "setosa" ~ Petal.Length + Petal.Width, iris, linear.output = FALSE,
	err.fct = my.err.fct)
# error!
```

**Comment by mnwright** [comment]
That's a bug in the CRAN version, which is already fixed on Github. You'll have to install the Github version until it is on CRAN, e.g. with

`devtools::install_github("bips-hb/neuralnet")`

**Comment by azhen1004** [comment]
Hello, I have encountered a similar problem, according to your answer to update the version, still unable to successfully build the neural network I need. Do you have related guidance documents to let me learn the details? Thanks very much.

**Comment by mnwright** [comment]
The change is still not on CRAN, sorry.

**Comment by azhen1004** [comment]
> The change is still not on CRAN, sorry.

Thank you for your reply.
